import { Hotel } from "@types";

const featuredPropertyData: Hotel[] = [
  {
    address: "Rio janeiro 213",
    cheapestPrice: 200,
    city: "Brasil",
    desc: "",
    distance: "10km",
    featured: true,
    name: "Kosama",
    photos: [],
    rooms: ["1", "123"],
    title: "Hotel kosama",
    type: "cabin",
  },
  {
    address: "Málaga 4234",
    cheapestPrice: 200,
    city: "Spain",
    desc: "",
    distance: "1km",
    featured: true,
    name: "Alvear",
    photos: [],
    rooms: ["1", "123", "54"],
    title: "Alvear residence",
    type: "cabin",
  },
  {
    address: "Schneider 1123",
    cheapestPrice: 400,
    city: "German",
    desc: "",
    distance: "5km",
    featured: true,
    name: "Viktor",
    photos: [],
    rooms: ["1", "123"],
    title: "Viktor apartment",
    type: "hotel",
  },
  {
    address: "431 muel",
    cheapestPrice: 200,
    city: "peru",
    desc: "",
    distance: "3km",
    featured: true,
    name: "mis amigos",
    photos: [],
    rooms: ["1", "123"],
    title: "mis amigos hotel",
    type: "resort",
  },
  {
    address: "caramai 145 a",
    cheapestPrice: 200,
    city: "colombia",
    desc: "",
    distance: "2km",
    featured: true,
    name: "Mirko",
    photos: [],
    rooms: ["1", "123"],
    title: "hotel mirko",
    type: "hotel",
  },
];
export { featuredPropertyData };
