export { Featured } from "./featured/Featured";
export { FeaturedProperties } from "./featuredProperty/FeatureProperty";
export { Footer } from "./footer/Footer";
export { Header } from "./header/Header";
export { MailList } from "./mailList/MailList";
export { Navbar } from "./navbar/Navbar";
export { PropertyList } from "./propertyList/PropertyList";
export { CalendarDays } from "./calendar/CalendarDays";
export { OptionsHotel } from "./optionsHotel/OptionsHotel";
export { Destination } from "./destination/Destination";
export { SearchItem } from "./searchItem/SearchItem";
export { RecreationOptions } from "./header/RecreationOptions";
export { default as HeaderLayout } from "./layouts/HeaderLayout";
export { default as Login } from "./login/Login";
export { default as NotFound } from "./errorBoundary/NotFound";
